#📌 Урок: Работа с файлами
##📖 Теоретический минимум

Текстовые файлы (.txt) - простые файлы с неструктурированным текстом

CSV (Comma-Separated Values) - табличные данные с разделителями

Excel (.xlsx, .xls) - электронные таблицы с расширенными возможностями

JSON - структурированные данные в формате ключ-значение

Бинарные файлы - изображения, PDF и другие нетекстовые форматы

# 🔹 Основные операции с файлами
Открытие/закрытие файла

Чтение данных

Запись данных

Обработка больших файлов


#📖 Материалы

https://vkvideo.ru/video-194554202_456239677

https://vkvideo.ru/video-194554202_456239682









# 🏆 Задания

## 1️⃣ Работа с текстовыми файлами
**Задача:**
 Создать текстовый файл, записать в него str данные и прочитать обратно

In [24]:
with open('example.txt', 'w') as file:
    file.write('оп хаха')


In [25]:
with open('example.txt', 'r') as file:
    a = file.read()
    print(a)

оп хаха



## 2️⃣ Работа с CSV файлами

**Задача:**

Создать CSV файл с табличными данными, записать и прочитать его



In [26]:
import csv
df = [
    ['УНИВЕРСИТЕТ', 'ГОРОД', 'ФОРМАТ'], 
    ['СПбПУ', 'СПб', 'очно'], 
    ['ВШЭ', 'Мск', 'дистанционно']
]

In [27]:
with open('df.csv', 'w', newline='', encoding= 'utf-8') as file:
    w = csv.writer(file)
    w.writerows(df)


In [28]:
with open('df.csv', 'r', encoding= 'utf-8') as file:
    r = csv.reader(file)
    for i in r: print(i)

['УНИВЕРСИТЕТ', 'ГОРОД', 'ФОРМАТ']
['СПбПУ', 'СПб', 'очно']
['ВШЭ', 'Мск', 'дистанционно']


## 3️⃣  Работа с Excel файлами
**Задача:** Создать Excel файл и прочитать данные из него

Используйте библиотеку pandas

---



In [29]:
import pandas as pd

df = [
    ['УНИВЕРСИТЕТ', 'ГОРОД', 'ФОРМАТ'], 
    ['СПбПУ', 'СПб', 'очно'], 
    ['ВШЭ', 'Мск', 'дистанционно']
]

In [30]:
df = pd.DataFrame(df)
df.to_excel('df.xlsx', index=False, engine='openpyxl')

In [31]:
print(pd.read_excel('df.xlsx', engine='openpyxl'))

             0      1             2
0  УНИВЕРСИТЕТ  ГОРОД        ФОРМАТ
1        СПбПУ    СПб          очно
2          ВШЭ    Мск  дистанционно



## 4️⃣  Чтение больших файлов по частям


**Задача:** Обработать файл построчно без загрузки в память целиком

Реализуйте чанки самостоятельно или воспользуйтесь chunk из pandas

---




In [35]:
d = 'large.csv' 
csize = 5

for i in pd.read_csv(d, chunksize=csize):
    print(i) 


   1 2 3 4 5
0  6 7 8 9 0
1  1 2 3 4 5
2  6 7 8 9 0
3  1 2 3 4 5
4  6 7 8 9 0
   1 2 3 4 5
5  1 2 3 4 5
6  6 7 8 9 0
7  1 2 3 4 5
8  6 7 8 9 0
9  1 2 3 4 5
    1 2 3 4 5
10  6 7 8 9 0
11  1 2 3 4 5
12  6 7 8 9 0
13  1 2 3 4 5
14  6 7 8 9 0
    1 2 3 4 5
15  1 2 3 4 5
16  6 7 8 9 0
17  1 2 3 4 5
18  6 7 8 9 0
19  1 2 3 4 5
    1 2 3 4 5
20  6 7 8 9 0
21  1 2 3 4 5
22  6 7 8 9 0
23  1 2 3 4 5
24  6 7 8 9 0
    1 2 3 4 5
25  1 2 3 4 5
26  6 7 8 9 0
27  1 2 3 4 5
28  6 7 8 9 0
29  1 2 3 4 5
    1 2 3 4 5
30  6 7 8 9 0
31  1 2 3 4 5
32  6 7 8 9 0
33  1 2 3 4 5
34  6 7 8 9 0
    1 2 3 4 5
35  1 2 3 4 5
36  6 7 8 9 0
37  1 2 3 4 5
38  6 7 8 9 0
39  1 2 3 4 5
    1 2 3 4 5
40  6 7 8 9 0
41  1 2 3 4 5
42  6 7 8 9 0
43  1 2 3 4 5
44  6 7 8 9 0
    1 2 3 4 5
45  1 2 3 4 5
46  6 7 8 9 0
47  1 2 3 4 5
48  6 7 8 9 0
49  1 2 3 4 5
    1 2 3 4 5
50  6 7 8 9 0
51  1 2 3 4 5
52  6 7 8 9 0
53  1 2 3 4 5
54  6 7 8 9 0
    1 2 3 4 5
55  1 2 3 4 5
56  6 7 8 9 0
57  1 2 3 4 5
58  6 7 8 9 0
59  1 2 3 4 5
    


## 5️⃣ Чтение JPEG файла
**Задача:**

Создайте изображение 21х21 пиксель в формате JPEG

Прочитайте JPEG файл в бинарном режиме

Выведете прочитанный файл как массив интенсивности пикселей

---


In [41]:
from PIL import Image
import numpy as np

w, h = 21, 21
d = np.random.randint(0, 256, (h, w, 3), dtype=np.uint8) 
image = Image.fromarray(d)
image.save('abc.jpg')


In [42]:
with open('abc.jpg', 'rb') as file:
    a = file.read()

ir = Image.open('abc.jpg')
arr = np.array(ir)
print(arr)


[[[119  59 173]
  [210 142 229]
  [188 101 135]
  ...
  [158 116  94]
  [171 144 125]
  [127 122 126]]

 [[ 79  23 122]
  [ 95  39 110]
  [145  87 102]
  ...
  [213 193 160]
  [133 120  88]
  [ 49  48  28]]

 [[ 99  54 119]
  [150 120 158]
  [112 111  93]
  ...
  [207 227 174]
  [ 31  49   0]
  [185 189 128]]

 ...

 [[180 175 133]
  [131 122  93]
  [147 125 127]
  ...
  [ 82  97 102]
  [206 180 189]
  [171  65  75]]

 [[199 184 181]
  [166 151 148]
  [134 119 114]
  ...
  [ 49  67  77]
  [113  93 102]
  [147  55  40]]

 [[175 158 202]
  [118 100 122]
  [107  84  66]
  ...
  [110 131 136]
  [138 127 123]
  [249 176 121]]]
